config/routes.rb
Rails.application.routes.draw do
  get 'clubs/index'

  get 'clubs/show'

  get 'clubs/edit'

  get 'clubs/create'

  get 'clubs/new'

  get 'clubs/delete'

  get 'clubs/gallery'

  get 'clubs/users'

  get 'news/index'

  get 'news/new'

  get 'news/create'

  get 'news/show'

  get 'news/edit'

  get 'news/update'

  get 'news/destroy'

  get 'notifications/reports'

  get 'notifications/show'

  get 'notifications/notices'

  get 'notifications/watch'

  get 'notifications/art'

  get 'notifications/journals'

  get 'notifications/polls'

  get 'notifications/comments'

  get 'admin/index'

  get 'stats/index'

  get 'journal/index'

  get 'journal/view'

  get 'journal/edit'

  get 'journal/update'

  get 'journal/new'

  get 'journal/delete'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  root 'index#index'

  post 'search', to: 'submission#search', as: 'submission-submit'
  post 'login' => 'session#create'
  get 'login' => 'session#create'
  post 'register' => 'user#create'
  delete 'logout' => 'session#destroy'

  get '/user/settings' => 'user_settings#index'
  get '/user/settings/personal' => 'user_settings#personal'
  get '/user/settings/integration' => 'user_settings#integration'
  get '/user/settings/deactivate' => 'user_settings#deactivate'
  post '/user/settings/avatar-update' => 'user_settings#avatarupdate'
  post '/user/settings/signature-update' => 'user_settings#signatureupdate'
  post '/user/settings/personalinfo-update' => 'user_settings#personalinfoupdate'
  get '/user/:user', to: 'user#view', as: 'user_view'
  patch '/user/settings/integration' => 'user_settings#integration_patch'

  # Submission
  get '/submission', to: 'submission#new', as: 'submission_create'
  get '/art/:slug', to: 'submission#view', as: 'submission_view'
  post '/submission', to: 'submission#upload', as: 'submission_upload'
  post '/submission/add-comment', to: 'submission#newcomment', as: 'submission_addcomment'
  patch '/art/:slug/favourite', to: 'submission#favourite', as: 'submission_favourite'
  get '/art/:slug/report', to: 'submission#report', as: 'submission_report'
  post '/art/:slug/report', to: 'submission#submitreport', as: 'submission_submitreport'

  # Submission API
  get '/api/submission/downloads/:id', to: 'api#submission_download', as: 'api_submission_download'

  # Tag Search
  get '/tag/:tag', to: 'search#tag', as: 'search_tag'

  # User
  get '/user/:user', to: 'user#view', as: 'view_user'
  get '/user/:user/gallery', to: 'user#gallery', as: 'view_gallery'

  get '/user/:user/favourites', to: 'user#favourites', as: 'view_favourites'

  get '/user/:user/watch', to: 'user#watch', as: 'watch_user'
  get '/user/:user/blacklist', to: 'user#blacklist', as: 'blacklist_user'

  get '/user/:user/polls', to: 'poll#polls', as: 'view_polls'
  post '/user/:user/polls', to: 'poll#polls_create', as: 'post_polls'
  post '/user/:user/poll/:id', to: 'poll#vote', as: 'vote_polls'
  delete '/user/:user/poll/:id', to: 'poll#delete', as: 'delete_polls'
  get 'user/:user/poll/edit/:id', to: 'poll#edit', as: 'edit_polls'
  patch 'user/:user/poll/edit/:id', to: 'poll#update', as: 'update_polls'

  get '/user/:user/journal', to: 'journal#index', as: 'view_journals'
  get '/user/:user/journal/:id', to: 'journal#view', as: 'view_journal'
  get '/user/:user/journal/edit/:id', to: 'journal#edit', as: 'edit_journal'
  patch '/user/:user/journal/edit/:id', to: 'journal#update', as: 'update_journal'
  post '/user/:user/journal/create', to: 'journal#new', as: 'create_journal'
  delete '/user/:user/journal/:id', to: 'journal#delete', as: 'delete_journal'
  post '/journal/comment/:id', to: 'journal#comment', as: 'comment_journal'

  get '/user/:user/stats', to: 'stats#index', as: 'view_stats'
  post '/send/message', to: 'user#sendmessage', as: 'send_message'

  # Admin
  get '/admin', to: 'admin#index', as: 'index_admin'

  # Notifications
  get '/notifications', to: 'notifications#show'
  get '/notifications/read/:id', to: 'notifications#read', as: 'read_pm'
  post '/notifications/pm/delete', to: 'notifications#pmdelete', as: 'delete_pm'
  post '/notifications/delete/:id', to: 'notifications#delete', as: 'delete_notification'
  get '/notifications/favs', to: 'notifications#favs', as: 'notification_favs'

  # News
  post '/news/create', to: 'news#create'
  get '/news/show/:slug', to: 'news#show', as: 'news_view'

  # Clubs
  get '/clubs', to: 'clubs#index', as: 'club_index'
  get '/club/:id', to: 'clubs#show', as: 'club_show'
  get '/clubs/new', to: 'clubs#new', as: 'club_new'
  post '/clubs/create', to: 'clubs#create', as: 'club_create'
  get '/club/:id/gallery', to: 'clubs#gallery', as: 'club_gallery'
  get '/club/:id/members', to: 'clubs#users', as: 'club_members'
  get '/club/:id/users', to: 'clubs#users', as: 'club_users'
  get '/club/:id/settings', to: 'clubs#settings', as: 'club_settings'
  patch '/club/:id/settings', to: 'clubs#settings_patch', as: 'club_settings_patch'
  post '/club/:id/comment', to: 'clubs#comment', as: 'club_comment'
  get '/club/:id/announcements', to: 'clubs#announcement', as: 'club_announcement'
  post '/club/:id/announcements', to: 'clubs#announcement_new', as: 'club_announcement_new'
  get '/club/:id/announcements/edit/:aid', to: 'clubs#announcement_edit', as: 'club_announcement_edit'
  patch '/club/:id/announcements/edit/:aid', to: 'clubs#announcement_patch', as: 'club_announcement_patch'
  get '/club/:id/announcements/:aid', to: 'clubs#announcement_show', as: 'club_announcement_show'
  delete '/club/:id/announcements/delete/:aid', to: 'clubs#announcement_delete', as: 'club_announcement_delete'
  get '/club/:id/membership/:uid', to: 'clubs#membership', as: 'club_membership'

  get '/policy/art/agreement', to: 'index#aaa', as: 'art_agreement'
  get '/policy/submission', to: 'index#subpolicy', as: 'submission_policy'
  get '/policy/terms', to: 'index#tos', as: 'terms_policy'

  get '/admin/users', to: 'admin#users', as: 'admin_users'
  post '/admin/users', to: 'admin#users_search', as: 'admin_users_search'

end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  before_action :require_login

  include PaginationHelper

  def show
    max = 15
    @offset = @offset = (params[:offset].nil?) ? 0 : params[:offset]
    @messages = @current_user.messages.limit(max).offset(@offset).order(id: :desc)
    genPaginationCreate(max, @current_user.messages)
  end

  def watch
    @reports = @current_user.notifications.where('tid = ?', 1)
  end

  def art
    @reports = @current_user.notifications.where('tid = ?', 5)
  end

  def journals
    @reports = @current_user.notifications.where('tid = ?', 4)
  end

  def polls
    @reports = @current_user.notifications.where('tid = ?', 6)
  end

  def comments
    @reports = @current_user.notifications.where('tid = ?', 2)
  end

  def reports
    @reports = @current_user.notifications.where('tid = ?', 0)
  end

  def read
    max = 15
    @offset = @offset = (params[:offset].nil?) ? 0 : params[:offset]
    @messages = @current_user.messages.limit(max).offset(@offset).order(id: :desc)
    genPaginationCreate(max, @current_user.messages)
    @message = Message.find_by_id(params[:id])
    @sender = User.find_by_id(@message.send_id)
  end

  def favs
    @reports = @current_user.notifications.where('tid = ?', 8)
  end

  def pmdelete
    messages = params[:message]
    messages.each do |k,v|
      @m = Message.where('id = ?', v)
      @m.destroy_all
    end
    redirect_to notifications_show_path
  end

  def delete
    id = params[:id]
    @r = Notification.find_by_id(id)

    if @current_user.id === @r.user_id
      @r.delete
    end

    redirect_to :back

  end
end

app/helpers/notification_helper.rb
module NotificationHelper

  # 0 = Report, 1 = Watch, 2 = Comment, 3 = Note, 4 = Journal, 5 = Art, 6 = Poll, 7 = News, 8 = Favourite

  def createNotification(type = 0, data = nil, notify = 0)
    @n = Notification.new
    @n.user_id = notify
    @n.tid = type
    @n.data = data.to_json
    @n.save
  end

  def deleteNotification(type = 0, data = nil)
    @n = Notification.where('data = ? AND tid = ?', data.to_json, type).destroy_all
  end

  def notificationCount(count)
    if count > 99
      return '99+'
    else
      return count
    end
  end


  def displayReportStatus(sid = 0)
    if sid.nil?
      sid = 0
    end

    statusName = nil
    statusType = nil

    case sid
      when 0
        statusName = 'Queued'
        statusType = 'default'
      when 1
        statusName = 'Pending'
        statusType = 'primary'
      when 2
        statusName = 'Approved'
        statusType = 'success'
      when 3
        statusName = 'Denied'
        statusType = 'danger'
      when 4
        statusName = 'Follow Up'
        statusType = 'info'
      when 5
        statusName = 'Warning'
        statusType = 'warning'
    end


    return content_tag(:span, statusName, class:['label', "label-#{statusType}"])

  end

end

app/views/notifications/_pms.html.erb
<div class="pm-list">
  <div class="select-area">
    <button class="btn btn-select" id="selectAllMessages">Select All</button>
    <div class="pull-right">
      <button class="btn btn-select" id="deleteMessages">Delete</button>
    </div>
    <div class="clearfix"></div>
  </div>
  <%= form_for :message, url: delete_pm_path, :html => {id: 'messagesForm'} do |f| %>
      <% @messages.each do |message| %>
          <div class="msg-container">
            <div class="msg-cb">
              <%= f.check_box "m_#{message.id}", {:class => 'cbmessage', :checked => false}, message.id, 0 %>
            </div>
            <div class="msg-data">
              <div class="pull-left">
                <div><strong><%= link_to message.title, read_pm_path(message.id) %></strong></div>
                <div>
                  <small>from <%= message.user.username %></small>
                </div>
              </div>
              <div class="pull-right">
                <div class="pm-date">
                  <small><%= time_ago_in_words message.created_at %></small>
                </div>
              </div>
              <div class="clearfix"></div>
            </div>
          </div>
      <% end %>
  <% end %>
  <%= render 'layouts/genpagination' %>
</div>
<% if action_name === 'show' %>
    <div class="pm-read">
      <div class="center-block text-center">
        <i class="fa fa-envelope fa-3x"></i>
        <h3>Please choose a message to read.</h3>
      </div>
    </div>
<% elsif action_name === 'read' %>
    <div class="pm-read">
      <div class="header">
        <div class="avatar">
          <div class="avatar-80">
            <%= image_tag grabGravatar(@sender.email) %>
          </div>
        </div>
        <div class="header-text">
          <h3><%= @message.title %></h3>
          <small>from <%= link_to @sender.username, view_user_path(@sender.username) %></small>
          <br/>
          <small>to <%= link_to @message.user.username, view_user_path(@message.user.username) %></small>
        </div>
      </div>
      <div class="data-text">
        <%= simple_format(@message.text) %>
      </div>
    </div>
<% end %>

app/views/notifications/_sidebar.html.erb
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li <%= activePage?('notifications', 'show') %>>
    <a href="<%= notifications_show_path %>"><i class="fa fa-archive"></i>Notifications</a></li>
    <li><a href="<%= notifications_reports_path %>"><i class="fa fa-flag"></i>Reports
      <span class="badge"><%= notificationCount @current_user.notifications.where('tid = ?', 0).count %></span></a></li>
    <li><a href="<%= notifications_watch_path %>"><i class="fa fa-eye"></i>Watches
      <span class="badge"><%= notificationCount @current_user.notifications.where('tid = ?', 1).count %></span></a></li>
    <li><a href="<%= notifications_art_path %>"><i class="fa fa-bars"></i>Art
      <span class="badge"><%= notificationCount @current_user.notifications.where('tid = ?', 5).count %></span></a></li>
    <li><a href="<%= notifications_comments_path %>"><i class="fa fa-comments"></i>Comments
      <span class="badge"><%= notificationCount @current_user.notifications.where('tid = ?', 2).count %></span></a></li>
    <li><a href="<%= notifications_journals_path %>"><i class="fa fa-pencil-square"></i>Journals
      <span class="badge"><%= notificationCount @current_user.notifications.where('tid = ?', 4).count %></span></a></li>
    <li><a href="<%= notifications_polls_path %>"><i class="fa fa-bar-chart"></i>Polls
      <span class="badge"><%= notificationCount @current_user.notifications.where('tid = ?', 6).count %></span></a></li>
    <li><a href="<%= notification_favs_path %>"><i class="fa fa-heart"></i>Favourites
      <span class="badge"><%= notificationCount @current_user.notifications.where('tid = ?', 8).count %></span></a></li>
  </ul>
</div>

app/views/notifications/art.html.erb
<div class="row">
  <div id="wrapper" class="notifications">
    <%= render 'notifications/sidebar' %>
    <div id="page-content-wrapper">
      <div class="gen-container" id="comments">
        <div class="header">Advertisement
          <div class="arrow-down"></div>
        </div>
      </div>
      <%= image_tag 'test/720x120.png', :class => 'center-block ad-image' %>

      <div class="gen-container" id="comments">
        <div class="header">New Art
          <div class="arrow-down"></div>
        </div>
      </div>
      <div class="art-body-container">
        <% @reports.each do |report| %>
            <% json = ActiveSupport::JSON.decode report.data %>
            <% subdata = Submission.find_by_id(json['id']) %>
            <div class="art-piece">
              <%= link_to '', delete_notification_path(report.id), {class: 'fa fa-times-circle art-delete', method: 'post', 'data-toggle' => 'tooltip', 'title' => 'Delete Notification', 'data-placement' => 'left'} %>
              <%= link_to submission_view_url(subdata.slug) do %>
                  <%= image_tag subdata.file_name %>
              <% end %>
              <div class="center-block text-center"><%= link_to subdata.title, submission_view_url(subdata.slug), {:class => 'text-center'} %></div>
              <div class="center-block text-center">by <%= link_to subdata.user.username, view_user_path(subdata.user.username) %></div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/notifications/comments.html.erb
<div class="row">
  <div id="wrapper" class="notifications">
    <%= render 'notifications/sidebar' %>
    <div id="page-content-wrapper">
      <div class="gen-container" id="comments">
        <div class="header">Advertisement
          <div class="arrow-down"></div>
        </div>
      </div>
      <%= image_tag 'test/720x120.png', :class => 'center-block ad-image' %>

      <div class="gen-container" id="comments">
        <div class="header">Comments
          <div class="arrow-down"></div>
        </div>
      </div>
      <div class="comments-container">
        <% @reports.each do |report| %>
            <% json = ActiveSupport::JSON.decode report.data %>
            <% @s = Submission.find_by_id(json['id']) %>
            <% offset_page = json['page'] * 25 %>
            <% comment_id = json['cid'] %>
            <div class="comment-row">
              <%= link_to 'Comment', submission_view_url(@s.slug, {'offset' => offset_page, :anchor => "comment-#{comment_id}"}) %> on
              <%= link_to @s.title, submission_view_url(@s.slug) %> by
              <%= link_to @s.user.username, user_view_path(@s.user.username) %>
              <div class="pull-right">
                <span class="label label-default"><%= dateFormat(report.created_at) %></span>
                <%= link_to '', delete_notification_path(report.id), {class: 'fa fa-times-circle art-delete', method: 'post', 'data-toggle' => 'tooltip', 'title' => 'Delete Notification', 'data-placement' => 'left'} %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/notifications/favs.html.erb
<div class="row">
  <div id="wrapper" class="notifications">
    <%= render 'notifications/sidebar' %>
    <div id="page-content-wrapper">
      <div class="gen-container" id="comments">
        <div class="header">Advertisement
          <div class="arrow-down"></div>
        </div>
      </div>
      <%= image_tag 'test/720x120.png', :class => 'center-block ad-image' %>

      <div class="gen-container" id="comments">
        <div class="header">Recent Favourited by People
          <div class="arrow-down"></div>
        </div>
      </div>
      <div class="comments-container">
        <% @reports.each do |report| %>
            <% json = ActiveSupport::JSON.decode report.data %>
            <% @s = Submission.find_by_id(json['id']) %>
            <% @u = FavouritesUser.find_by_user_id(json['from']) %>
            <div class="comment-row">
              <%= link_to @u.user.username, user_view_path(@u.user.username) %> has added
              <strong><%= link_to @s.title, submission_view_url(@s.slug) %></strong>
              to their favourites
              <div class="pull-right">
                <span class="label label-default"><%= dateFormat(report.created_at) %></span>
                <%= link_to '', delete_notification_path(report.id), {class: 'fa fa-times-circle art-delete', method: 'post', 'data-toggle' => 'tooltip', 'title' => 'Delete Notification', 'data-placement' => 'left'} %>
              </div>
              <div class="clearfix"></div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/notifications/journals.html.erb
<div class="row">
  <div id="wrapper" class="notifications">
    <%= render 'notifications/sidebar' %>
    <div id="page-content-wrapper">
      <div class="gen-container" id="comments">
        <div class="header">Advertisement
          <div class="arrow-down"></div>
        </div>
      </div>
      <%= image_tag 'test/720x120.png', :class => 'center-block ad-image' %>

      <div class="gen-container" id="comments">
        <div class="header">Journals
          <div class="arrow-down"></div>
        </div>
      </div>
      <div class="comments-container">
        <% @reports.each do |report| %>
            <% json = ActiveSupport::JSON.decode report.data %>
            <% @s = Journal.find_by_id(json['id']) %>
            <div class="comment-row">
              New Journal
              <strong><%= link_to @s.title, view_journal_path(@s.user.username, @s.id) %></strong>
              by
              <%= link_to @s.user.username, user_view_path(@s.user.username) %>
              <div class="pull-right">
                <span class="label label-default"><%= dateFormat(report.created_at) %></span>
                <%= link_to '', delete_notification_path(report.id), {class: 'fa fa-times-circle art-delete', method: 'post', 'data-toggle' => 'tooltip', 'title' => 'Delete Notification', 'data-placement' => 'left'} %>
              </div>
              <div class="clearfix"></div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/notifications/polls.html.erb
<div class="row">
  <div id="wrapper" class="notifications">
    <%= render 'notifications/sidebar' %>
    <div id="page-content-wrapper">
      <div class="gen-container" id="comments">
        <div class="header">Advertisement
          <div class="arrow-down"></div>
        </div>
      </div>
      <%= image_tag 'test/720x120.png', :class => 'center-block ad-image' %>

      <div class="gen-container" id="comments">
        <div class="header">Polls
          <div class="arrow-down"></div>
        </div>
      </div>
      <div class="comments-container">
        <% @reports.each do |report| %>
            <% json = ActiveSupport::JSON.decode report.data %>
            <% @s = Poll.find_by_id(json['id']) %>
            <div class="comment-row">
              New Poll
              <strong><%= link_to @s.title, view_polls_path(@s.user.username) %></strong>
              by
              <%= link_to @s.user.username, user_view_path(@s.user.username) %>
              <div class="pull-right">
                <span class="label label-default"><%= dateFormat(report.created_at) %></span>
                <%= link_to '', delete_notification_path(report.id), {class: 'fa fa-times-circle art-delete', method: 'post', 'data-toggle' => 'tooltip', 'title' => 'Delete Notification', 'data-placement' => 'left'} %>
              </div>
              <div class="clearfix"></div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/notifications/read.html.erb
<div class="row">
  <div id="wrapper" class="notifications">
    <%= render 'notifications/sidebar' %>
    <div id="page-content-wrapper">
      <div class="gen-container" id="comments">
        <div class="header">Advertisement
          <div class="arrow-down"></div>
        </div>
      </div>
      <%= image_tag 'test/720x120.png', :class => 'center-block ad-image' %>

      <div class="gen-container" id="comments">
        <div class="header">Private Messages
          <div class="arrow-down"></div>
        </div>
      </div>
      <div class="pm-container">
        <%= render 'notifications/pms' %>
      </div>
    </div>
  </div>
</div>

app/views/notifications/reports.html.erb
<div class="row">
  <div id="wrapper" class="notifications">
    <%= render 'notifications/sidebar' %>
    <div id="page-content-wrapper">
      <div class="gen-container" id="comments">
        <div class="header">Advertisement
          <div class="arrow-down"></div>
        </div>
      </div>
      <%= image_tag 'test/720x120.png', :class => 'center-block ad-image' %>

      <div class="gen-container" id="comments">
        <div class="header">Reports
          <div class="arrow-down"></div>
        </div>
      </div>
      <div class="reportaa-container">
        <% @reports.each do |report| %>
            <% json = ActiveSupport::JSON.decode report.data %>
            <% subdata = @current_user.submissions.find_by_id(json['id']) %>
            <div class="report-container">
              <div class="report-body">
                <div class="pull-left">
                  <%= link_to subdata.title, submission_view_url(subdata.slug) %> has been Reported
                </div>
                <div class="pull-right">
                  <%= displayReportStatus(subdata.report.status) %>
                  <span class="label label-default"><%= dateFormat(report.created_at) %></span>
                  <%= link_to '', delete_notification_path(report.id), {class: 'fa fa-times-circle', method: 'post', 'data-toggle' => 'tooltip', 'title' => 'Delete Notification', 'data-placement' => 'left'} %>
                </div>
                <div class="clearfix"></div>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/notifications/show.html.erb
<div class="row">
  <div id="wrapper" class="notifications">
    <%= render 'notifications/sidebar' %>
    <div id="page-content-wrapper">
      <div class="gen-container" id="comments">
        <div class="header">Advertisement
          <div class="arrow-down"></div>
        </div>
      </div>
      <%= image_tag 'test/720x120.png', :class => 'center-block ad-image' %>

      <div class="gen-container" id="comments">
        <div class="header">Private Messages
          <div class="arrow-down"></div>
        </div>
      </div>
      <div class="pm-container">
        <%= render 'notifications/pms' %>
      </div>
    </div>
  </div>
</div>

app/views/notifications/watch.html.erb
<div class="row">
  <div id="wrapper" class="notifications">
    <%= render 'notifications/sidebar' %>
    <div id="page-content-wrapper">
      <div class="gen-container" id="comments">
        <div class="header">Advertisement
          <div class="arrow-down"></div>
        </div>
      </div>
      <%= image_tag 'test/720x120.png', :class => 'center-block ad-image' %>

      <div class="gen-container" id="comments">
        <div class="header">Watches
          <div class="arrow-down"></div>
        </div>
      </div>
      <div class="reportaa-container">
        <% @reports.each do |report| %>
            <% json = ActiveSupport::JSON.decode report.data %>
            <% subdata = User.find_by_id(json['from']) %>
            <div class="report-container">
              <div class="report-body">
                <div class="pull-left">
                  <%= link_to subdata.username, user_view_path(subdata.username) %> started watching you
                </div>
                <div class="pull-right">
                  <%= content_tag(:span, dateFormat(report.created_at), {:class => 'label label-default'}) %>
                  <%= link_to '', delete_notification_path(report.id), {class: 'fa fa-times-circle', method: 'post', 'data-toggle' => 'tooltip', 'title' => 'Delete Notification', 'data-placement' => 'left'} %>
                </div>
                <div class="clearfix"></div>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>