config/routes.rb
Rails.application.routes.draw do
  get 'clubs/index'

  get 'clubs/show'

  get 'clubs/edit'

  get 'clubs/create'

  get 'clubs/new'

  get 'clubs/delete'

  get 'clubs/gallery'

  get 'clubs/users'

  get 'news/index'

  get 'news/new'

  get 'news/create'

  get 'news/show'

  get 'news/edit'

  get 'news/update'

  get 'news/destroy'

  get 'notifications/reports'

  get 'notifications/show'

  get 'notifications/notices'

  get 'notifications/watch'

  get 'notifications/art'

  get 'notifications/journals'

  get 'notifications/polls'

  get 'notifications/comments'

  get 'admin/index'

  get 'stats/index'

  get 'journal/index'

  get 'journal/view'

  get 'journal/edit'

  get 'journal/update'

  get 'journal/new'

  get 'journal/delete'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  root 'index#index'

  post 'search', to: 'submission#search', as: 'submission-submit'
  post 'login' => 'session#create'
  get 'login' => 'session#create'
  post 'register' => 'user#create'
  delete 'logout' => 'session#destroy'

  get '/user/settings' => 'user_settings#index'
  get '/user/settings/personal' => 'user_settings#personal'
  get '/user/settings/integration' => 'user_settings#integration'
  get '/user/settings/deactivate' => 'user_settings#deactivate'
  post '/user/settings/avatar-update' => 'user_settings#avatarupdate'
  post '/user/settings/signature-update' => 'user_settings#signatureupdate'
  post '/user/settings/personalinfo-update' => 'user_settings#personalinfoupdate'
  get '/user/:user', to: 'user#view', as: 'user_view'
  patch '/user/settings/integration' => 'user_settings#integration_patch'

  # Submission
  get '/submission', to: 'submission#new', as: 'submission_create'
  get '/art/:slug', to: 'submission#view', as: 'submission_view'
  post '/submission', to: 'submission#upload', as: 'submission_upload'
  post '/submission/add-comment', to: 'submission#newcomment', as: 'submission_addcomment'
  patch '/art/:slug/favourite', to: 'submission#favourite', as: 'submission_favourite'
  get '/art/:slug/report', to: 'submission#report', as: 'submission_report'
  post '/art/:slug/report', to: 'submission#submitreport', as: 'submission_submitreport'

  # Submission API
  get '/api/submission/downloads/:id', to: 'api#submission_download', as: 'api_submission_download'

  # Tag Search
  get '/tag/:tag', to: 'search#tag', as: 'search_tag'

  # User
  get '/user/:user', to: 'user#view', as: 'view_user'
  get '/user/:user/gallery', to: 'user#gallery', as: 'view_gallery'

  get '/user/:user/favourites', to: 'user#favourites', as: 'view_favourites'

  get '/user/:user/watch', to: 'user#watch', as: 'watch_user'
  get '/user/:user/blacklist', to: 'user#blacklist', as: 'blacklist_user'

  get '/user/:user/polls', to: 'poll#polls', as: 'view_polls'
  post '/user/:user/polls', to: 'poll#polls_create', as: 'post_polls'
  post '/user/:user/poll/:id', to: 'poll#vote', as: 'vote_polls'
  delete '/user/:user/poll/:id', to: 'poll#delete', as: 'delete_polls'
  get 'user/:user/poll/edit/:id', to: 'poll#edit', as: 'edit_polls'
  patch 'user/:user/poll/edit/:id', to: 'poll#update', as: 'update_polls'

  get '/user/:user/journal', to: 'journal#index', as: 'view_journals'
  get '/user/:user/journal/:id', to: 'journal#view', as: 'view_journal'
  get '/user/:user/journal/edit/:id', to: 'journal#edit', as: 'edit_journal'
  patch '/user/:user/journal/edit/:id', to: 'journal#update', as: 'update_journal'
  post '/user/:user/journal/create', to: 'journal#new', as: 'create_journal'
  delete '/user/:user/journal/:id', to: 'journal#delete', as: 'delete_journal'
  post '/journal/comment/:id', to: 'journal#comment', as: 'comment_journal'

  get '/user/:user/stats', to: 'stats#index', as: 'view_stats'
  post '/send/message', to: 'user#sendmessage', as: 'send_message'

  # Admin
  get '/admin', to: 'admin#index', as: 'index_admin'

  # Notifications
  get '/notifications', to: 'notifications#show'
  get '/notifications/read/:id', to: 'notifications#read', as: 'read_pm'
  post '/notifications/pm/delete', to: 'notifications#pmdelete', as: 'delete_pm'
  post '/notifications/delete/:id', to: 'notifications#delete', as: 'delete_notification'
  get '/notifications/favs', to: 'notifications#favs', as: 'notification_favs'

  # News
  post '/news/create', to: 'news#create'
  get '/news/show/:slug', to: 'news#show', as: 'news_view'

  # Clubs
  get '/clubs', to: 'clubs#index', as: 'club_index'
  get '/club/:id', to: 'clubs#show', as: 'club_show'
  get '/clubs/new', to: 'clubs#new', as: 'club_new'
  post '/clubs/create', to: 'clubs#create', as: 'club_create'
  get '/club/:id/gallery', to: 'clubs#gallery', as: 'club_gallery'
  get '/club/:id/members', to: 'clubs#users', as: 'club_members'
  get '/club/:id/users', to: 'clubs#users', as: 'club_users'
  get '/club/:id/settings', to: 'clubs#settings', as: 'club_settings'
  patch '/club/:id/settings', to: 'clubs#settings_patch', as: 'club_settings_patch'
  post '/club/:id/comment', to: 'clubs#comment', as: 'club_comment'
  get '/club/:id/announcements', to: 'clubs#announcement', as: 'club_announcement'
  post '/club/:id/announcements', to: 'clubs#announcement_new', as: 'club_announcement_new'
  get '/club/:id/announcements/edit/:aid', to: 'clubs#announcement_edit', as: 'club_announcement_edit'
  patch '/club/:id/announcements/edit/:aid', to: 'clubs#announcement_patch', as: 'club_announcement_patch'
  get '/club/:id/announcements/:aid', to: 'clubs#announcement_show', as: 'club_announcement_show'
  delete '/club/:id/announcements/delete/:aid', to: 'clubs#announcement_delete', as: 'club_announcement_delete'
  get '/club/:id/membership/:uid', to: 'clubs#membership', as: 'club_membership'

  get '/policy/art/agreement', to: 'index#aaa', as: 'art_agreement'
  get '/policy/submission', to: 'index#subpolicy', as: 'submission_policy'
  get '/policy/terms', to: 'index#tos', as: 'terms_policy'

  get '/admin/users', to: 'admin#users', as: 'admin_users'
  post '/admin/users', to: 'admin#users_search', as: 'admin_users_search'

end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :user
  has_many :submission_comments
  has_many :favourites_users
  has_one :report
  mount_uploader :file_name, SubmissionUploader

  # Validation
  validates :file_name, presence: true
  validates :title, presence: true, length: {minimum: 3, maximum: 32}, allow_nil: false
  validates :description, presence: true, allow_nil: false
  validates :tags, presence: true, allow_nil: true
  # validates :filters, presence: true, allow_nil: true

end

app/controllers/submission_controller.rb
class SubmissionController < ApplicationController

  include DateAndTime
  include PaginationHelper
  include NotificationHelper
  include FavouritesHelper
  include SubmissionHelper
  include IntegrationHelper

  before_action :require_login, except: ['view']

  def search

  end

  def new
  end

  def upload
    submission = Submission.new
    submission.user_id = @current_user.id
    submission.title = params[:submission][:title]
    submission.description = params[:submission][:description]
    submission.r18_rating = (params[:submission][:rating] == 'r18') ? 1 : 0
    submission.general_rating = 1
    submission.tags = params[:submission][:tags]
    submission.filters = nil
    submission.file_name = params[:submission][:submission_image]
    submission.patreon = params[:submission][:patreon]

    # Default to 0
    submission.views = 0
    submission.favourites = 0
    submission.downloads = 0
    submission.comments = 0
    submission.reported = false

    filter_array = []
    if !params[:filter][:violence].nil?
      filter_array.push 'violence'
    end

    if !params[:filter][:drugs].nil?
      filter_array.push 'drugs'
    end

    if !params[:filter][:language].nil?
      filter_array.push 'language'
    end

    if !params[:filter][:crime].nil?
      filter_array.push 'crime'
    end

    if !params[:filter][:furry].nil?
      filter_array.push 'furry'
    end

    submission.filters = filter_array.to_json

    if submission.save
      slug = params[:submission][:title].parameterize
      submission.update_attribute('slug', slug + '-' + submission.id.to_s)

      clubs = params[:submission][:club]
      if !clubs.nil?
        clubs.each do |k, v|
          @club = Club.find_by_id(v)
          @club.club_submissions.create(submission_id: submission.id)
        end
      end

      # Send out Notifications based on Users Watch list....
      @w = UserWatch.where('uid = ?', @current_user.id)
      @w.each do |watch|
        createNotification(5, {type: 'art', id: submission.id, slug: slug}, watch.user_id)
      end

      redirect_to submission_view_path(submission.slug)
    else
      submission.errors.full_messages.each do |message|
        flash[:danger] = message
      end
      redirect_to submission_create_url
    end
  end

  def view
    @submission = Submission.find_by_slug(params[:slug])
    @tags = @submission.tags.split(',')

    paginationCreate(25, SubmissionComment, 'submission_id', @submission.id)

    @resolution = @submission.resolution.split(';')

    @download = @submission.file_name.url

    @submission.update_attribute('views', (@submission.views + 1))

    # If not Exist... go to homepage
    if @submission.nil?
      redirect_to root_url
    end

  end

  def newcomment

    @s = Submission.find_by_id(params[:submission_comments][:submission_id])

    @sc = SubmissionComment.new
    @sc.user_id = @current_user.id
    @sc.submission_id = params[:submission_comments][:submission_id]
    @sc.comment = params[:submission_comments][:comment]
    if @sc.save
      modCommentCount(@s, 1)
      @sxc = SubmissionComment.where('submission_id = ?', @s.id)
      pagec = @sxc.count / 25;
      createNotification(2, {type: 'art', id: @s.id, from: @current_user.id, cid: @sc.id, page: pagec}, @s.user.id)
      redirect_to submission_view_url(@s.slug)
    else

    end
  end

  def favourite
    id = Submission.find_by_slug(params[:slug]).id
    @s = Submission.find_by_slug(params[:slug])
    uid = @current_user.id

    # Check if Already Exists...
    @fc = FavouritesUser.where(:user_id => uid, :submission_id => id)
    if @fc.empty?
      @f = FavouritesUser.new
      @f.user_id = uid
      @f.submission_id = id
      @f.save
      createNotification(8, {type: 'art', id: id, from: uid}, @s.user.id)
      modSubmissionFavourites(@s, 1)
    else
      FavouritesUser.where(:user_id => uid, :submission_id => id).destroy_all
      deleteNotification(8, {type: 'art', id: id, from: uid})
      modSubmissionFavourites(@s, -1)
    end

    redirect_to submission_view_path(params[:slug])
  end

  def report
    @s = Submission.find_by_slug(params[:slug])

    # Do not allow multiple reports
    if !@s.report.blank?
      redirect_to submission_view_path(@s.slug)
    end

  end

  def submitreport
    @s = Submission.find_by_slug(params[:slug])
    @r = Report.new
    @r.submission_id = @s.id
    @r.description = params[:report_submission][:report_desc]
    @r.reason = params[:report_submission][:reason].to_json
    @r.uid = @current_user.id
    if @r.save
      createNotification(0, {type: 'art', id: @s.id}, @s.user.id)
      @s.update_attribute('reported', true)
    end
  end

end

app/helpers/submission_helper.rb
module SubmissionHelper
  def modCommentCount(model, mod)
    model.update_attribute('comments', model.comments + mod)
  end
end

app/views/submission/_pagination.html.erb
<div class="pagination center-block text-center">
  <% if @count > 0 %>
      <ul class="list-inline list-unstyled">
        <% if @currentPage > 0 %>
            <li><a href="?offset=<%= @previousPage %>"><i class="fa fa-step-backward"></i> Previous</a></li>
            <li><a href="?offset=<%= @startPage %>"><i class="fa fa-fast-backward"></i></a></li>
        <% end %>
        <% (@currentPage..@maxPages).each do |i| %>
            <% if i < @totalPages %>
                <li><a href="?offset=<%= i * @maxRecords %>">
                  <% if i == @currentPage %>
                      <strong><%= i + 1 %></strong>
                  <% else %>
                      <%= i + 1 %>
                  <% end %>
                </a></li>
            <% end %>
        <% end %>
        <% if @currentPage < @totalPages %>
            <li><a href="?offset=<%= @lastPage %>"><i class="fa fa-fast-forward"></i></a></li>
            <li><a href="?offset=<%= @nextPage %>">Next <i class="fa fa-step-forward"></i></a></li>
        <% end %>
      </ul>
  <% end %>
</div>

app/views/submission/_sidebar.html.erb
<% if @submission.patreon %>
    <h5 class="text-center"><strong>Support me on Patreon</strong></h5>
    <div id="patreon-integration">
      <a href="<%= patreon(@submission.user) %>" target="_blank">
        <%= image_tag 'network-apps/bmpop.png' %>
      </a>
    </div>
<% end %>

<% if logged_in? && @current_user.id != @submission.user.id %>
    <% if @submission.favourites_users.where(user_id: @current_user.id).empty? %>
        <%= link_to submission_favourite_path(@submission.slug), :class => 'btn btn-fav', :role => 'button', method: 'patch' do %>
            <i class="fa fa-star"></i><span>Add To Favourites</span>
        <% end %>
    <% else %>
        <%= link_to submission_favourite_path(@submission.slug), :class => 'btn btn-fav toggled', :role => 'button', method: 'patch' do %>
            <i class="fa fa-star"></i><span>Add To Favourites</span>
        <% end %>
    <% end %>
<% end %>

<%= link_to @download, :class => 'btn btn-cloud', :id => 'downloadSubmission', 'data-id' => @submission.id, 'data-url' => api_submission_download_url(@submission.id) do %>
    <i class="fa fa-cloud-download"></i><span>Download</span>
<% end %>

<div class="metainfo">
  <h4 class="metainfo-heading"><strong>Details</strong></h4>
  <dl>
    <dt>Submitted on</dt>
    <dd><span><%= time_ago_in_words(@submission.created_at) %> ago</span></dd>
    <dt>Size</dt>
    <dd><span><%= number_to_human_size(@submission.size) %></span></dd>
    <dt>Resolution</dt>
    <dd><span><%= @resolution[0] + 'x' + @resolution[1] %></span></dd>
  </dl>
</div>

<div class="sp center-block">
  <div class="spi"></div>
</div>

<div class="metainfo">
  <h4 class="metainfo-heading"><strong>Stats</strong></h4>
  <dl>
    <dt>Views</dt>
    <dd><span><%= @submission.views %></span></dd>
    <dt>Favourites</dt>
    <dd><span><%= @submission.favourites %></span></dd>
    <dt>Comments</dt>
    <dd><span><%= @submission.comments %></span></dd>
    <dt>Downloads</dt>
    <dd><span><%= @submission.downloads %></span></dd>
  </dl>
</div>

<div class="sp center-block">
  <div class="spi"></div>
</div>

<!--<div class="report-area">-->
<!--<a href="#"><i class="fa fa-exclamation-triangle"></i> Report</a>-->
<!--</div>-->

<% if logged_in? %>
    <%= link_to submission_report_path(@submission.slug), :class => 'btn btn-report' do %>
        <i class="fa fa-exclamation-triangle"></i><span>Report</span>
    <% end %>
<% end %>

app/views/submission/new.html.erb
<h3>Submission</h3>
<div class="submission-mb">
  <%= form_for(:submission, url: submission_upload_url, :html => {:id => 'submission-form', :class => 'form', :multipart => true}) do |f| %>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
      <div class="main-body">
        <h4>Creation</h4>
        <div class="submission-container">
          <div class="center-block text-center">
            <div>
              <canvas id="imgthumbcanvas" style="display: none;"></canvas>
            </div>
            <%= f.file_field :submission_image, :class => 'hide', :id => 'file-upload-select' %>
            <a href="#" id="upload-file" class="btn btn-lg btn-choose-file" role="button">Choose
              a File Upload</a>
            <div class="rating clearfix center-block text-center">
              <div class="rating-label">Contains adult material?</div>
              <div class="rating-select">
                <label class="radio-inline">
                  <!--<input type="radio" value="r18" name="rating"> Yes-->
                  <%= f.radio_button :rating, 'r18' %> Yes
                </label>
                <label class="radio-inline">
                  <!--<input type="radio" value="general" name="rating"> No-->
                  <%= f.radio_button :rating, 'general' %> No
                </label>
                <span class="label label-danger">(Required)</span>
              </div>
            </div>
          </div>
        </div>
        <div class="content-information-input">
          <div class="header">
            <%= f.text_field :title, :placeholder => 'Title', :class => 'form-control' %>
          </div>
          <div class="body">
            <%= f.text_area :description, :class => 'form-control', :id => 'tb_description' %>
            <div class="tagsarea">
              <%= f.text_field :tags, :class => 'form-control', :id => 'tags' %>
              <small>Seperate your tags with <kbd>,</kbd> or <kbd>return</kbd> / <kbd>enter</kbd></small>
            </div>
          </div>
        </div>

        <h4>Filters</h4>
        <div class="content-information-input">
          <div class="checkbox-filters">
            <div>
              <label data-toggle="tooltip" data-placement="top" title="Includes blood, violence, horror, things that may be considered inappropriate by sensitive views.">
                <%= check_box :filter, "violence" %> Violence
              </label>
            </div>
            <div>
              <label data-toggle="tooltip" data-placement="top" title="Includes scenes where tabacoo, alcohol, stimulants, narcotics or presciprtion drugs are used, implied, or paraphernalia or analogous to any of the above are used.">
                <%= check_box :filter, "drugs" %> Drugs, smoking, alcoholism
              </label>
            </div>
            <div>
              <label data-toggle="tooltip" data-placement="top" title="Includes discriminatory language, conversation and content not suitable for minors, or opinion that may cause discomfort to viewers.">
                <%= check_box :filter, "language" %> Strong language / Sensitive Themes
              </label>
            </div>
            <div>
              <label data-toggle="tooltip" data-placement="top" title="Includes depictions of criminal acts, torture, sex crimes, prostitution, suicide/self-injury.">
                <%= check_box :filter, "crime" %> Criminal acts
              </label>
            </div>
            <div>
              <label data-toggle="tooltip" data-placement="top" title="Includes animals with human-like characteristics and personalities.">
                <%= check_box :filter, "furry" %> Furry
              </label>
            </div>
          </div>
        </div>

        <h4>Club Selection</h4>
        <% @current_user.clubs.each do |club| %>
            <a href="#" class="club-select" onclick="return false" data-club-id="<%= club.id %>">
              <%= f.check_box "club[#{club.id}]", {:class => 'hide', 'data-id' => club.id}, club.id, nil %>
              <div class="club-img pull-left" style="background-image: url(<%= club.club_extend.avatar %>)">
                <img src="" alt="" width="1" height="1">
              </div>
              <span class="pull-left club-name"><%= club.name %></span>
              <span class="clearfix"></span>
            </a>
        <% end %>

        <div class="clearfix"></div>
        <p style="margin-top: 10px;">
          Please read our <strong><%= link_to "Submissions Policy", submission_policy_path, :target => '_blank' %></strong>,
          <strong><%= link_to "Terms of Service", terms_policy_path, :target => '_blank' %></strong>, and
          <strong><%= link_to "Art Acceptance Agreement", art_agreement_path, :target => '_blank' %></strong> before uplading any materials
        </p>

        <button type="submit" class="submission-submit-btn">Submit</button>
      </div>
      <div class="right-apps">
        <h4>Apps</h4>
        <% if !@current_user.user_extend.patreon.blank? %>
            <a href="#" onclick="return false">
              <div class="apps disabled" id="patreon">
                <%= f.check_box :patreon, {:checked => false, :class => 'hide'}, false %>
                <%= image_tag "network-apps/bmpop.png" %>
                <p>
                  <small>You can show that you are connected to Patreon and allow users to become your patron @ patreon.
                    This
                    makes it easier to apply the logo to your submission so you don't have to fill in the information
                    everytime.
                  </small>
                </p>
              </div>
            </a>
        <% end %>
      </div>
  <% end %>
</div>

app/views/submission/report.html.erb
<%= form_for :report_submission, url: submission_submitreport_path(@s.slug) do |f| %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="pull-left">
          <h4>Reporting Submission <%= @s.title %></h4>
        </div>
        <div class="pull-right">
          <h5>
            Created by <%= link_to @s.user.username, view_user_path(@s.user.username) %>
            <br/>
            <small>On <%= @s.created_at.strftime("%c") %></small>
          </h5>
        </div>
        <div class="clearfix"></div>
        <hr>

        <div class="center-block text-center report-image-view">
          <%= image_tag @s.file_name %>
        </div>

        <h3>Why are you reporting this image ?</h3>
        <div class="form-group">
          <%= f.text_area :report_desc, :class => 'form-control', :required => 'required' %>
        </div>

        <h3>Please check all that apply:</h3>
        <div class="form-group">
          <div class="checkbox">
            <label>
              <%= f.check_box 'reason[adult_filter]', {}, '1', '0' %> Missing Adult Filter
            </label>
          </div>
          <div class="checkbox">
            <label>
              <%= f.check_box 'reason[shota]', {}, '1', '0' %> Contains Shota
            </label>
          </div>
          <div class="checkbox">
            <label>
              <%= f.check_box 'reason[female]', {}, '1', '0' %> Contains Female in Sexual Activity
            </label>
          </div>
          <div class="checkbox">
            <label>
              <%= f.check_box 'reason[stolen]', {}, '1', '0' %> Stolen Artwork
            </label>
          </div>
          <div class="checkbox">
            <label>
              <%= f.check_box 'reason[ip]', {}, '1', '0' %> Intellectual Property
            </label>
          </div>
          <div class="checkbox">
            <label>
              <%= f.check_box 'reason[dmca]', {}, '1', '0' %> DMCA Request
            </label>
          </div>
          <div class="checkbox">
            <label>
              <%= f.check_box 'reason[other]', {}, '1', '0' %> Other
            </label>
          </div>
        </div>
        <p>
          <strong>By submitting this report, you verify that this report was made with good conscience. If you are found
            to be
            submission reports without found reasons you will be penalized which may lead up to a warning, ban or
            perma-ban
            from the site.</strong>
        </p>
        <%= f.submit "Send Report", :class => 'btn btn-submit-report pull-right' %>
      </div>
    </div>
<% end %>

app/views/submission/view.html.erb
<div class="submission-content">
  <div class="main-content">
    <!--<img src="" class="submission-image" data-irid="" data-cirid="">-->
    <div id="image-cell" class="center-block text-center">
      <%= image_tag @submission.file_name %>
    </div>
    <div id="submission-content-data">
      <div class="avatar pull-left">
        <%= image_tag grabGravatar @submission.user.email %>
      </div>
      <div class="data pull-left">
        <h3><%= link_to @submission.title, submission_view_url(@submission.slug) %></h3>
        <h4>by <%= link_to @submission.user.username, user_view_url(@submission.user.username) %></h4>
        <div>
          <small>&copy; <%= @submission.created_at.year %> <%= @submission.user.username %></small>
        </div>
        <ul class="list-inline pull-left">
          <% @tags.each do |tag| %>
              <li class="submission-tags-list"><%= link_to "#" + tag, search_tag_url(tag) %></li>
          <% end %>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="clearfix"></div>
      <div class="submission-description-case">
        <div class="submission-description">
          <%= simple_format(@submission.description) %>
        </div>
      </div>
    </div>
    <div class="comment">
      <div>
        <small>
          <%= link_to @submission.user.username, user_view_url(@submission.user.username) %> -
          Add Comment :
        </small>
      </div>
      <div>
        <div class="comment-new">
          <%= form_for :submission_comments, url: submission_addcomment_path, method: 'post' do |f| %>
              <%= f.hidden_field :submission_id, :value => @submission.id %>
              <div class="avatar">
                <%= image_tag grabGravatar @submission.user.email %>
              </div>
              <div class="comment">
                <div class="comment-arrow-left"></div>
                <%= f.text_area :comment, :class => 'form-control comments-textarea' %>
              </div>
              <div class="pull-right">
                <button type="submit">Post Comment</button>
              </div>
          <% end %>
        </div>
      </div>
      <div class="comments-list">
        <% @comments.each do |comment| %>
            <div class="comment-display clearfix" data-id="comment-<%= comment.id %>" id="comment-<%= comment.id %>">
              <div class="avatar">
                <%= image_tag grabGravatar comment.user.email %>
              </div>
              <div class="comment-block">
                <div class="left-arrow"></div>
                <div class="text">
                  <small class="pull-right">#<%= comment.id %></small>
                  <h5>
                    <%= link_to comment.user.username, user_view_url(comment.user_id) %><br />
                    <small data-toggle="tooltip" data-placement="top" title="<%= time_ago_in_words(comment.created_at) %> ago"><%= comment.created_at.strftime('%b %d, %Y') %></small>
                  </h5>
                  <div class="comment-data" data-id="<%= comment.id %>">
                    <%= simple_format comment.comment %>
                    <a href="#" data-comment-id="<%= comment.id %>" class="comment-read-more center-block text-center reveal-comment hide">Read More</a>
                  </div>
                </div>
              </div>
            </div>
        <% end %>
      </div>
      <%= render 'submission/pagination' %>
    </div>
  </div>
  <div class="sidebar-content">
    <%= render 'submission/sidebar' %>
  </div>
  <div class="sidebar-bg"></div>
  <div class="clearfix"></div>
</div>