config/routes.rb
Rails.application.routes.draw do
  get 'clubs/index'

  get 'clubs/show'

  get 'clubs/edit'

  get 'clubs/create'

  get 'clubs/new'

  get 'clubs/delete'

  get 'clubs/gallery'

  get 'clubs/users'

  get 'news/index'

  get 'news/new'

  get 'news/create'

  get 'news/show'

  get 'news/edit'

  get 'news/update'

  get 'news/destroy'

  get 'notifications/reports'

  get 'notifications/show'

  get 'notifications/notices'

  get 'notifications/watch'

  get 'notifications/art'

  get 'notifications/journals'

  get 'notifications/polls'

  get 'notifications/comments'

  get 'admin/index'

  get 'stats/index'

  get 'journal/index'

  get 'journal/view'

  get 'journal/edit'

  get 'journal/update'

  get 'journal/new'

  get 'journal/delete'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  root 'index#index'

  post 'search', to: 'submission#search', as: 'submission-submit'
  post 'login' => 'session#create'
  get 'login' => 'session#create'
  post 'register' => 'user#create'
  delete 'logout' => 'session#destroy'

  get '/user/settings' => 'user_settings#index'
  get '/user/settings/personal' => 'user_settings#personal'
  get '/user/settings/integration' => 'user_settings#integration'
  get '/user/settings/deactivate' => 'user_settings#deactivate'
  post '/user/settings/avatar-update' => 'user_settings#avatarupdate'
  post '/user/settings/signature-update' => 'user_settings#signatureupdate'
  post '/user/settings/personalinfo-update' => 'user_settings#personalinfoupdate'
  get '/user/:user', to: 'user#view', as: 'user_view'
  patch '/user/settings/integration' => 'user_settings#integration_patch'

  # Submission
  get '/submission', to: 'submission#new', as: 'submission_create'
  get '/art/:slug', to: 'submission#view', as: 'submission_view'
  post '/submission', to: 'submission#upload', as: 'submission_upload'
  post '/submission/add-comment', to: 'submission#newcomment', as: 'submission_addcomment'
  patch '/art/:slug/favourite', to: 'submission#favourite', as: 'submission_favourite'
  get '/art/:slug/report', to: 'submission#report', as: 'submission_report'
  post '/art/:slug/report', to: 'submission#submitreport', as: 'submission_submitreport'

  # Submission API
  get '/api/submission/downloads/:id', to: 'api#submission_download', as: 'api_submission_download'

  # Tag Search
  get '/tag/:tag', to: 'search#tag', as: 'search_tag'

  # User
  get '/user/:user', to: 'user#view', as: 'view_user'
  get '/user/:user/gallery', to: 'user#gallery', as: 'view_gallery'

  get '/user/:user/favourites', to: 'user#favourites', as: 'view_favourites'

  get '/user/:user/watch', to: 'user#watch', as: 'watch_user'
  get '/user/:user/blacklist', to: 'user#blacklist', as: 'blacklist_user'

  get '/user/:user/polls', to: 'poll#polls', as: 'view_polls'
  post '/user/:user/polls', to: 'poll#polls_create', as: 'post_polls'
  post '/user/:user/poll/:id', to: 'poll#vote', as: 'vote_polls'
  delete '/user/:user/poll/:id', to: 'poll#delete', as: 'delete_polls'
  get 'user/:user/poll/edit/:id', to: 'poll#edit', as: 'edit_polls'
  patch 'user/:user/poll/edit/:id', to: 'poll#update', as: 'update_polls'

  get '/user/:user/journal', to: 'journal#index', as: 'view_journals'
  get '/user/:user/journal/:id', to: 'journal#view', as: 'view_journal'
  get '/user/:user/journal/edit/:id', to: 'journal#edit', as: 'edit_journal'
  patch '/user/:user/journal/edit/:id', to: 'journal#update', as: 'update_journal'
  post '/user/:user/journal/create', to: 'journal#new', as: 'create_journal'
  delete '/user/:user/journal/:id', to: 'journal#delete', as: 'delete_journal'
  post '/journal/comment/:id', to: 'journal#comment', as: 'comment_journal'

  get '/user/:user/stats', to: 'stats#index', as: 'view_stats'
  post '/send/message', to: 'user#sendmessage', as: 'send_message'

  # Admin
  get '/admin', to: 'admin#index', as: 'index_admin'

  # Notifications
  get '/notifications', to: 'notifications#show'
  get '/notifications/read/:id', to: 'notifications#read', as: 'read_pm'
  post '/notifications/pm/delete', to: 'notifications#pmdelete', as: 'delete_pm'
  post '/notifications/delete/:id', to: 'notifications#delete', as: 'delete_notification'
  get '/notifications/favs', to: 'notifications#favs', as: 'notification_favs'

  # News
  post '/news/create', to: 'news#create'
  get '/news/show/:slug', to: 'news#show', as: 'news_view'

  # Clubs
  get '/clubs', to: 'clubs#index', as: 'club_index'
  get '/club/:id', to: 'clubs#show', as: 'club_show'
  get '/clubs/new', to: 'clubs#new', as: 'club_new'
  post '/clubs/create', to: 'clubs#create', as: 'club_create'
  get '/club/:id/gallery', to: 'clubs#gallery', as: 'club_gallery'
  get '/club/:id/members', to: 'clubs#users', as: 'club_members'
  get '/club/:id/users', to: 'clubs#users', as: 'club_users'
  get '/club/:id/settings', to: 'clubs#settings', as: 'club_settings'
  patch '/club/:id/settings', to: 'clubs#settings_patch', as: 'club_settings_patch'
  post '/club/:id/comment', to: 'clubs#comment', as: 'club_comment'
  get '/club/:id/announcements', to: 'clubs#announcement', as: 'club_announcement'
  post '/club/:id/announcements', to: 'clubs#announcement_new', as: 'club_announcement_new'
  get '/club/:id/announcements/edit/:aid', to: 'clubs#announcement_edit', as: 'club_announcement_edit'
  patch '/club/:id/announcements/edit/:aid', to: 'clubs#announcement_patch', as: 'club_announcement_patch'
  get '/club/:id/announcements/:aid', to: 'clubs#announcement_show', as: 'club_announcement_show'
  delete '/club/:id/announcements/delete/:aid', to: 'clubs#announcement_delete', as: 'club_announcement_delete'
  get '/club/:id/membership/:uid', to: 'clubs#membership', as: 'club_membership'

  get '/policy/art/agreement', to: 'index#aaa', as: 'art_agreement'
  get '/policy/submission', to: 'index#subpolicy', as: 'submission_policy'
  get '/policy/terms', to: 'index#tos', as: 'terms_policy'

  get '/admin/users', to: 'admin#users', as: 'admin_users'
  post '/admin/users', to: 'admin#users_search', as: 'admin_users_search'

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :club_users
  has_many :user_comments
  has_many :clubs, :through => :club_users
  has_many :journals
  has_many :polls
  has_many :roles, :through => :role_users
  has_many :role_users
  has_many :blacklists
  has_many :favourites_users
  has_many :notifications
  has_many :user_watches
  has_many :messages
  has_many :submissions
  has_many :newses
  has_one :user_extend

  # Validation
  validates :username, presence: true, length: {minimum: 6, maximum: 12}, allow_nil: false, uniqueness: true
  validates :password, presence: true, confirmation: true, allow_nil: false, length: {minimum: 6, maximum: 16}
  validates :email, presence: true, uniqueness: true
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_action :require_login, :only => [:watch, :blacklist]

  include PaginationHelper
  include SessionHelper
  include NotificationHelper

  def create
    # Check if 18!
    birthday = params[:birthday]
    d = Date.new(birthday['(1i)'].to_i, birthday['(2i)'].to_i, birthday['(3i)'].to_i)
    c = Date.today
    if (c.year - d.year < 18)
      flash[:danger] = 'You must be 18 or older to join this site'
    end

    # Check if Accepted TOS
    accept_tos = params[:accept_tos]
    if accept_tos.nil?
      flash[:danger] = 'You must accept our TOS'
    end

    @user = User.new(user_params)
    if @user.save
      @user.role_users.create(user_id: @user.id, role_id: 5)
      @user.create_user_extend(user_id: @user.id, dob: d)
      @userid = login_user @user
    else
      @user.errors.full_messages.each do |message|
        flash[:danger] = message
      end
    end

    redirect_to root_url

  end

  def view
    @user = User.find_by_username(params[:user])
    @last5 = Submission.where('user_id' => @user.id).order(id: :desc).limit(5)
    @journal = @user.journals.order(id: :desc).limit(1)[0]

    paginationCreate(10, UserComment, 'user_id', @user.id)
  end

  def gallery
    @user = User.find_by_username(params[:user])
    @gallery = Submission.where('user_id = ?', @user.id).order(created_at: :desc)
    @count = @gallery.count
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def watch
    if params[:user] === @current_user.username
      redirect_to view_user_path(params[:user])
    end

    # Check if Exists...
    @u = User.find_by_username(params[:user])
    @w = UserWatch.where('user_id = ? AND uid = ?', @current_user.id, @u.id)
    if @w.blank? || @w.empty?
      model = UserWatch.new
      model.user_id = @current_user.id
      model.uid = @u.id
      if model.save
        createNotification(1, {type: 'watch', user: @u.username, from: @current_user.id}, @u.id)
      end
    else
      if @w.delete_all
        deleteNotification(1, {type: 'watch', user: @u.username, from: @current_user.id})
      end
    end

    redirect_to view_user_path(@u.username)

  end

  def blacklist
    if params[:user] === @current_user.username
      redirect_to view_user_path(params[:user])
    end

    # Check if Exists...
    @u = User.find_by_username(params[:user])
    @b = Blacklist.where('user_id = ? AND blacklist_user_id = ?', @current_user.id, @u.id)
    if @b.blank? || @b.empty?
      model = Blacklist.new
      model.user_id = @current_user.id
      model.blacklist_user_id = @u.id
      model.save
    else
      @b.delete_all

    end
    redirect_to view_user_path(@u.username)
  end

  def sendmessage
    @u = User.find_by_username(params[:message][:recipient])
    uid = params[:message][:uid]

    @m = Message.new
    @m.user_id = @u.id
    @m.send_id = uid
    @m.title = params[:message][:title]
    @m.text = params[:message][:text]
    @m.deleted = false
    @m.read = false
    @m.send_deleted = false
    if @m.save
      redirect_to view_user_path(@u.username)
    end
  end

  def favourites
    @user = User.find_by_username(params[:user])
    @favourites = FavouritesUser.where('user_id = ?', @user.id)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_tabs.html.erb
<div class="tabs">
  <ul>
    <li <%= activePage?('user', 'view') %>><a href="<%= user_view_path(@user.username) %>">Profile</a></li>
    <li <%= activePage?('user', 'gallery') %>><a href="<%= view_gallery_path(@user.username) %>">Gallery</a></li>
    <li <%= activePage?('poll', 'polls') %>><a href="<%= view_polls_path(@user.username) %>">Polls</a></li>
    <li <%= activePage?('journal', 'index') || activePage?('journal', 'view') || activePage?('journal', 'edit') %>>
      <a href="<%= view_journals_path(@user.username) %>">Journal</a></li>
    <li><a href="<%= view_favourites_path(@user.username) %>">Favourites</a></li>
    <li <%= activePage?('stats', 'index') %>><a href="<%= view_stats_path(@user.username) %>">Stats</a></li>
  </ul>
</div>

app/views/user/_userheader.html.erb
<div class="user-header clearfix">
  <div class="avatar">
    <%= link_to view_user_path(@user.username) do %>
        <%= image_tag grabGravatar(@user.email), :class => 'avatar-80' %>
    <% end %>
  </div>
  <div class="naming-block">
    <h3><%= @user.username %><br/>
      <small>Random Title</small>
    </h3>
  </div>
  <%= render('user/tabs') %>
  <% if logged_in? && @current_user.id != @user.id %>
      <div class="pull-left">
        <%= link_to '', :class => 'btn btn-message btn-fl toggled', :role => 'button', :id => 'sendMessage', 'data-username' => @user.username, 'data-toggle' => 'modal', 'data-target' => '#send-message-modal' do %>
            <i class="fa fa-sticky-note"></i><span>New Note</span>
        <% end %>
      </div>
      <div class="pull-right mr-20">
        <% if @current_user.user_watches.where('user_id = ? and uid = ?', @current_user.id, @user.id).count > 0 %>
            <%= link_to watch_user_path(@user.username), :class => 'btn btn-watch btn-fl toggled', :role => 'button' do %>
                <i class="fa fa-heart"></i><span>Watching</span>
            <% end %>
        <% else %>
            <%= link_to watch_user_path(@user.username), :class => 'btn btn-watch btn-fl', :role => 'button' do %>
                <i class="fa fa-heart"></i><span>Watch</span>
            <% end %>
        <% end %>
        <% if @current_user.blacklists.where('user_id = ? and blacklist_user_id = ?', @current_user.id, @user.id).count > 0 %>
            <%= link_to blacklist_user_path(@user.username), :class => 'btn btn-blacklist btn-fl toggled', :role => 'button' do %>
                <i class="fa fa-square"></i><span>Unblock</span>
            <% end %>
        <% else %>
            <%= link_to blacklist_user_path(@user.username), :class => 'btn btn-blacklist btn-fl', :role => 'button' do %>
                <i class="fa fa-square"></i><span>Block</span>
            <% end %>
        <% end %>
      </div>
      <div class="clearfix"></div>
  <% end %>
</div>

<% if logged_in? %>
    <div id="send-message-modal" class="modal fade" tabindex="-1" role="dialog">
      <%= form_for :message, url: send_message_path do |f| %>
          <%= f.hidden_field :uid, :value => @current_user.id %>
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Send Message</h4>
              </div>
              <div class="modal-body">

                <div class="form-group">
                  <%= f.text_field :recipient, :class => 'form-control', :value => @user.username, :readonly => 'readonly' %>
                </div>
                <div class="form-group">
                  <%= f.text_field :title, :class => 'form-control', :placeholder => 'Title' %>
                </div>
                <div class="form-group">
                  <%= f.text_area :text, :class => 'form-control' %>
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Send</button>
              </div>
            </div>
          </div>
      <% end %>
    </div>
<% end %>

app/views/user/favourites.html.erb
<div class="row userpage">
  <%= render('user/userheader') %>

  <div id="gallery-page" class="clearfix" style="padding: 0 0 0 20px;">
    <div class="display" style="width: 100%;">
      <h4>Favourites</h4>
      <div class="gallery-container">
        <% @favourites.each do |favourite| %>
            <div class="gallery-image-container">
              <%= link_to submission_view_url(favourite.submission.slug) do %>
                  <div class="image-container" style="background-image: url(<%= favourite.submission.file_name %>);">
                    <img src="<%= favourite.submission.file_name %>" alt="<%= favourite.submission.title %>">
                  </div>
                  <div class="gallery-links text-center">
                    <h5><%= favourite.submission.title %></h5>
                    <i class="fa fa-comments"></i><%= pluralize?("Comment", favourite.submission.comments) %>
                  </div>
              <% end %>
            </div>
        <% end %>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

app/views/user/gallery.html.erb
<div class="row userpage">
  <%= render('user/userheader') %>

  <div id="gallery-page" class="clearfix">
    <div class="folders">
      <h4>Folders</h4>
      <div class="folder-container">
      </div>
    </div>
    <div class="display">
      <h4>Gallery</h4>
      <div class="gallery-container">
        <% @gallery.each do |gallery| %>
            <div class="gallery-image-container">
              <%= link_to submission_view_url(gallery.slug) do %>
                  <div class="image-container" style="background-image: url(<%= gallery.file_name %>);">
                    <img src="<%= gallery.file_name %>" alt="<%= gallery.title %>">
                  </div>
                  <div class="gallery-links text-center">
                    <h5><%= gallery.title %></h5>
                    <i class="fa fa-comments"></i><%= pluralize?("Comment", gallery.comments) %>
                  </div>
              <% end %>
            </div>
        <% end %>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

app/views/user/view.html.erb
<div class="row userpage">
  <%= render('user/userheader') %>

  <div class="container-fluid user-profile-data">
    <div class="art-display">
      <% if @last5.count > 0 %>
          <% @last5.each do |last| %>
              <div class="user-space-container">
                <div class="user-space-header">
                  <div class="user-space-arrow-down"></div>
                  <strong><%= last.title %></strong>
                </div>
                <div class="user-space-body">
                  <a href="<%= submission_view_url(last.slug) %>">
                    <%= image_tag last.file_name, :class => 'center-block' %>
                    <span class="center-block text-center">
                  <i class="fa fa-comments"></i><%= pluralize?("Comment", last.comments) %>
                </span>
                  </a>
                </div>
              </div>
          <% end %>
      <% else %>
          <div class="user-space-container"></div>
      <% end %>
    </div>

    <div class="journal-display-misc">
      <% if !@journal.nil? || !@journal.blank? %>
          <div class="journal-container">
            <div class="journal-header">
              <h2><%= link_to @journal.title, view_journal_path(@user.username, @journal.id) %></h2>
          <span>by <%= link_to @journal.user.username, view_user_path(@journal.user.username) %>
            , <%= @journal.created_at.strftime('%b %d, %Y, %I:%m %p') %></span>
            </div>
            <div class="journal-body">
              <%= simple_format(@journal.text) %>
            </div>
          </div>
          <div class="journal-footer">
            <div class="links clearfix">
              <div class="pull-left">
                <h5><%= link_to @journal.title, view_journal_path(@user.username, @journal.id) %></h5>
                <div>
                  <%= link_to view_journal_path(@journal.user.username, @journal.id) do %>
                      <i class="fa fa-comments"></i><%= pluralize?('Comment', @journal.journal_comments.count) %>
                  <% end %>
                </div>
              </div>
              <div class="pull-right">
                <strong><%= @journal.created_at.strftime('%b %d, %Y') %></strong>
              </div>
            </div>
            <a href="<%= view_journals_path(@user.username) %>" class="text-center center-block view-journals">View
              Journals</a>
          </div>
      <% end %>

      <div class="gen-container" id="userinfo">
        <div class="header">Profile ID
          <div class="arrow-down"></div>
        </div>
        <div class="inner">
        </div>
      </div>

      <div class="gen-container" id="comments">
        <div class="header">Comments
          <div class="arrow-down"></div>
        </div>
      </div>
      <div class="comment">
        <div>
          <div class="comment-new">
            <%= form_for :submission_comments, url: submission_addcomment_path, method: 'post' do |f| %>
                <%= f.hidden_field :user_id, :value => @user.id %>
                <div class="avatar">
                  <%= image_tag grabGravatar(@user.email) %>
                </div>
                <div class="comment">
                  <div class="comment-arrow-left"></div>
                  <%= f.text_area :comment, :class => 'form-control comments-textarea' %>
                </div>
                <div class="pull-right">
                  <button type="submit">Post Comment</button>
                </div>
            <% end %>
          </div>
        </div>
        <div class="comments-list">
          <% @comments.each do |comment| %>
              <div class="comment-display clearfix">
                <div class="avatar">
                  <%= image_tag grabGravatar comment.user.email %>
                </div>
                <div class="comment-block">
                  <div class="left-arrow"></div>
                  <div class="text">
                    <h5>
                      <%= link_to comment.user.username, user_view_url(comment.user.username) %>
                      <small data-toggle="tooltip" data-placement="top" title="<%= time_ago_in_words(comment.created_at) %> ago"><%= comment.created_at.strftime('%b %d, %Y') %></small>
                    </h5>
                    <p class="comment-data">
                      <%= comment.comment %>
                    </p>
                  </div>
                </div>
              </div>
          <% end %>
        </div>
        <%= render 'submission/pagination' %>
      </div>
    </div>
  </div>
</div>