config/routes.rb
Rails.application.routes.draw do
  get 'clubs/index'

  get 'clubs/show'

  get 'clubs/edit'

  get 'clubs/create'

  get 'clubs/new'

  get 'clubs/delete'

  get 'clubs/gallery'

  get 'clubs/users'

  get 'news/index'

  get 'news/new'

  get 'news/create'

  get 'news/show'

  get 'news/edit'

  get 'news/update'

  get 'news/destroy'

  get 'notifications/reports'

  get 'notifications/show'

  get 'notifications/notices'

  get 'notifications/watch'

  get 'notifications/art'

  get 'notifications/journals'

  get 'notifications/polls'

  get 'notifications/comments'

  get 'admin/index'

  get 'stats/index'

  get 'journal/index'

  get 'journal/view'

  get 'journal/edit'

  get 'journal/update'

  get 'journal/new'

  get 'journal/delete'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  root 'index#index'

  post 'search', to: 'submission#search', as: 'submission-submit'
  post 'login' => 'session#create'
  get 'login' => 'session#create'
  post 'register' => 'user#create'
  delete 'logout' => 'session#destroy'

  get '/user/settings' => 'user_settings#index'
  get '/user/settings/personal' => 'user_settings#personal'
  get '/user/settings/integration' => 'user_settings#integration'
  get '/user/settings/deactivate' => 'user_settings#deactivate'
  post '/user/settings/avatar-update' => 'user_settings#avatarupdate'
  post '/user/settings/signature-update' => 'user_settings#signatureupdate'
  post '/user/settings/personalinfo-update' => 'user_settings#personalinfoupdate'
  get '/user/:user', to: 'user#view', as: 'user_view'
  patch '/user/settings/integration' => 'user_settings#integration_patch'

  # Submission
  get '/submission', to: 'submission#new', as: 'submission_create'
  get '/art/:slug', to: 'submission#view', as: 'submission_view'
  post '/submission', to: 'submission#upload', as: 'submission_upload'
  post '/submission/add-comment', to: 'submission#newcomment', as: 'submission_addcomment'
  patch '/art/:slug/favourite', to: 'submission#favourite', as: 'submission_favourite'
  get '/art/:slug/report', to: 'submission#report', as: 'submission_report'
  post '/art/:slug/report', to: 'submission#submitreport', as: 'submission_submitreport'

  # Submission API
  get '/api/submission/downloads/:id', to: 'api#submission_download', as: 'api_submission_download'

  # Tag Search
  get '/tag/:tag', to: 'search#tag', as: 'search_tag'

  # User
  get '/user/:user', to: 'user#view', as: 'view_user'
  get '/user/:user/gallery', to: 'user#gallery', as: 'view_gallery'

  get '/user/:user/favourites', to: 'user#favourites', as: 'view_favourites'

  get '/user/:user/watch', to: 'user#watch', as: 'watch_user'
  get '/user/:user/blacklist', to: 'user#blacklist', as: 'blacklist_user'

  get '/user/:user/polls', to: 'poll#polls', as: 'view_polls'
  post '/user/:user/polls', to: 'poll#polls_create', as: 'post_polls'
  post '/user/:user/poll/:id', to: 'poll#vote', as: 'vote_polls'
  delete '/user/:user/poll/:id', to: 'poll#delete', as: 'delete_polls'
  get 'user/:user/poll/edit/:id', to: 'poll#edit', as: 'edit_polls'
  patch 'user/:user/poll/edit/:id', to: 'poll#update', as: 'update_polls'

  get '/user/:user/journal', to: 'journal#index', as: 'view_journals'
  get '/user/:user/journal/:id', to: 'journal#view', as: 'view_journal'
  get '/user/:user/journal/edit/:id', to: 'journal#edit', as: 'edit_journal'
  patch '/user/:user/journal/edit/:id', to: 'journal#update', as: 'update_journal'
  post '/user/:user/journal/create', to: 'journal#new', as: 'create_journal'
  delete '/user/:user/journal/:id', to: 'journal#delete', as: 'delete_journal'
  post '/journal/comment/:id', to: 'journal#comment', as: 'comment_journal'

  get '/user/:user/stats', to: 'stats#index', as: 'view_stats'
  post '/send/message', to: 'user#sendmessage', as: 'send_message'

  # Admin
  get '/admin', to: 'admin#index', as: 'index_admin'

  # Notifications
  get '/notifications', to: 'notifications#show'
  get '/notifications/read/:id', to: 'notifications#read', as: 'read_pm'
  post '/notifications/pm/delete', to: 'notifications#pmdelete', as: 'delete_pm'
  post '/notifications/delete/:id', to: 'notifications#delete', as: 'delete_notification'
  get '/notifications/favs', to: 'notifications#favs', as: 'notification_favs'

  # News
  post '/news/create', to: 'news#create'
  get '/news/show/:slug', to: 'news#show', as: 'news_view'

  # Clubs
  get '/clubs', to: 'clubs#index', as: 'club_index'
  get '/club/:id', to: 'clubs#show', as: 'club_show'
  get '/clubs/new', to: 'clubs#new', as: 'club_new'
  post '/clubs/create', to: 'clubs#create', as: 'club_create'
  get '/club/:id/gallery', to: 'clubs#gallery', as: 'club_gallery'
  get '/club/:id/members', to: 'clubs#users', as: 'club_members'
  get '/club/:id/users', to: 'clubs#users', as: 'club_users'
  get '/club/:id/settings', to: 'clubs#settings', as: 'club_settings'
  patch '/club/:id/settings', to: 'clubs#settings_patch', as: 'club_settings_patch'
  post '/club/:id/comment', to: 'clubs#comment', as: 'club_comment'
  get '/club/:id/announcements', to: 'clubs#announcement', as: 'club_announcement'
  post '/club/:id/announcements', to: 'clubs#announcement_new', as: 'club_announcement_new'
  get '/club/:id/announcements/edit/:aid', to: 'clubs#announcement_edit', as: 'club_announcement_edit'
  patch '/club/:id/announcements/edit/:aid', to: 'clubs#announcement_patch', as: 'club_announcement_patch'
  get '/club/:id/announcements/:aid', to: 'clubs#announcement_show', as: 'club_announcement_show'
  delete '/club/:id/announcements/delete/:aid', to: 'clubs#announcement_delete', as: 'club_announcement_delete'
  get '/club/:id/membership/:uid', to: 'clubs#membership', as: 'club_membership'

  get '/policy/art/agreement', to: 'index#aaa', as: 'art_agreement'
  get '/policy/submission', to: 'index#subpolicy', as: 'submission_policy'
  get '/policy/terms', to: 'index#tos', as: 'terms_policy'

  get '/admin/users', to: 'admin#users', as: 'admin_users'
  post '/admin/users', to: 'admin#users_search', as: 'admin_users_search'

end

app/views/layouts/_genpagination.html.erb
<div class="pagination center-block text-center">
  <% if @count > 0 %>
      <ul class="list-inline list-unstyled">
        <% if @currentPage > 0 %>
            <li><a href="?offset=<%= @previousPage %>"><i class="fa fa-step-backward"></i> Previous</a></li>
            <li><a href="?offset=<%= @startPage %>"><i class="fa fa-fast-backward"></i></a></li>
        <% end %>
        <% (@currentPage..@maxPages).each do |i| %>
            <% if i < @totalPages %>
                <li><a href="?offset=<%= i * @maxRecords %>">
                  <% if i == @currentPage %>
                      <strong><%= i + 1 %></strong>
                  <% else %>
                      <%= i + 1 %>
                  <% end %>
                </a></li>
            <% end %>
        <% end %>
        <% if @currentPage < @totalPages %>
            <li><a href="?offset=<%= @lastPage %>"><i class="fa fa-fast-forward"></i></a></li>
            <li><a href="?offset=<%= @nextPage %>">Next <i class="fa fa-step-forward"></i></a></li>
        <% end %>
      </ul>
  <% end %>
</div>

app/views/layouts/_loginmodal.html.erb
<% if !logged_in? %>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Join Bara Box</h4>
          </div>
          <div class="modal-body">
            <%= form_for(:user, url: register_path, :html => {:id => 'form-register', :class => 'form-horizontal'}) do |f| %>
                <div class="form-group">
                  <%= f.label :username %>
                  <%= f.text_field :username, :class => 'form-control' %>
                </div>
                <div class="form-group">
                  <%= f.label :email %>
                  <%= f.text_field :email, :class => 'form-control' %>
                </div>
                <div class="form-group">
                  <%= f.label :password %>
                  <%= f.password_field :password, :class => 'form-control' %>
                </div>
                <div class="form-group">
                  <%= f.label :password_confirmation %>
                  <%= f.password_field :password_confirmation, :class => 'form-control' %>
                </div>
                <div class="form-group">
                  <%= f.label :birthday %>
                  <div class="dob">
                    <%= date_select :birthday, "", {:order => [:month, :day, :year], :prompt => {:day => 'Day', :month => 'Month', :year => 'Year'}, :start_year => 1900} %>
                  </div>
                </div>
                <div class="form-group">
                  <%= f.label :gender %>
                  <div>
                    <%= select_tag :gender, options_for_select([['Male', 1], ['Female', 2]]) %>
                  </div>
                </div>
                <hr>
                <div class="checkbox">
                  <label for="">
                    <%= check_box_tag :accept_tos %> I have read and agreed to the Terms of Service
                  </label>
                </div>
                <br>
                <div class="form-group center-block text-center">
                  <!--<a href="#" class="btn btn-gradient-mint" id="user-signup">-->
                  <!--<span>Sign Up</span>-->
                  <!--</a>-->
                  <%= f.submit "Submit", :class => 'btn btn-gradient-mint lrg' %>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default <%= (controller_name == 'notifications') ? 'navbar-fixed-top' : '' %>">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_url %>">
        <%= image_tag 'logo.png', :class => 'pull-left' %>
        <span class="pull-right">Bara <strong>Box</strong></span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-main">
        <li><a href="<%= news_index_path %>">News</a></li>
        <li><a href="https://barabox.freshdesk.com/support/home" target="_blank">Support</a></li>
        <% if logged_in? %>
            <li><%= link_to "Submit", submission_create_url, :class => 'btn btn-info btn-sm btn-submit' %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <img class="avatar-icon-sm img-rounded" src="<%= grabGravatar(@current_user.email) %>" alt="<%= grabGravatar(@current_user.email) %>">
                <%= @current_user.username %>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="<%= user_view_path(@current_user.username) %>"><i class="fa fa-info-circle"></i> Profile</a>
                </li>
                <li role="separator" class="divider"></li>
                <li><a href="<%= submission_create_url %>"><i class="fa fa-paint-brush"></i> Submit</a></li>
                <li><%= link_to user_settings_path do %> <i class="fa fa-cogs"></i> Settings
                  <% end %></li>
                <li role="separator" class="divider"></li>
                <li>
                  <%= link_to logout_path, :method => :delete do %>
                      <i class="fa fa-sign-out"></i> Logout
                  <% end %>
                </li>
              </ul>
            </li>
            <li class="dropdown" id="messaging">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-envelope" style="font-size: 20px;"></i>
                <small><%= mbTotalCount %></small>
              </a>
              <ul class="dropdown-menu">
                <li><a href="<%= notifications_show_path %>"><i class="fa fa-inbox"></i> All Notifications</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="<%= news_index_path %>"><i class="fa fa-bullhorn"></i> News
                  <small><%= mbNewsCount %></small>
                </a></li>
                <li><a href="<%= notifications_watch_path %>"><i class="fa fa-eye"></i> Watches
                  <small><%= mbWatchCount %></small>
                </a></li>
                <li><a href="<%= notifications_comments_path %>"><i class="fa fa-commenting"></i> Comments
                  <small><%= mbCommentCount %></small>
                </a></li>
              </ul>
            </li>
            <li><%= link_to content_tag(:i, '', {:class => 'fa fa-group'}), club_index_path %></li>
            <% if isAdmin? %>
                <li><a href="<%= index_admin_url %>"><i class="fa fa-star fa-spin" style="font-size: 20px;"></i></a>
                </li>
            <% end %>
        <% else %>
            <li><a href="#" data-target="#myModal" data-toggle="modal">Join</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login</a>
              <div class="dropdown-menu">
                <%= form_for(:session, url: login_path, :html => {:id => 'form-login'}) do |f| %>
                    <div class="form-group">
                      <%= f.label :username %>
                      <%= f.text_field :username, :class => 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= f.label :password %>
                      <%= f.password_field :password_digest, :class => 'form-control' %>
                    </div>
                    <div class="form-group">
                      <%= f.submit "Login", :class => 'btn btn-gradient lrg' %>
                    </div>
                <% end %>
              </div>
            </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t("title") %></title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <link href='https://fonts.googleapis.com/css?family=Lato:400,300,700,100' rel='stylesheet' type='text/css'>
</head>

<body>
<%= render "layouts/navbar" %>
<%= render "layouts/loginmodal" %>
<div class="container">
  <div class="row">
  </div>
</div>
<div class="container-fluid">
  <%= yield %>
</div>
<br/><br/>
<% if params[:debug] === '1' %>
    <%= debug(params) if Rails.env.development? %>
    <%= debug(session[:user_id]) if Rails.env.development? %>
<% end %>
</body>
</html>